version: "3.8"

services:
  reactweb-patient:
    image: image-service
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: image-service-nodeJS
    ports:
      - "8084:8084"
    volumes:
      - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

volumes:
  node_modules: